### ISSUE TITLE
Добавить более качественный скриншот из Google Docs

### ISSUE THREAD

**Issue by ro31337** [ro31337/rubyisforfun_ru#1]
Страница ~217:

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1477672/164123061-6896632e-4942-442b-a1a4-7595952cb4ce.png">

Скриншот был сделан из Google Docs, но надо сделать его (например) на Макбуке с ретиной и заменить существующий файл. Это необходимо для того, чтобы при распечатке было качественное изображение.

**Comment by Orniflop** [comment]
https://github.com/Orniflop/rubyisforfun_ru.git  Добавил картинку
<img width="423" alt="065-2-poster" src="https://user-images.githubusercontent.com/101870927/164179492-d1ff198e-5ed3-4d59-985d-c3a1a89c3cf1.png">

**Comment by ro31337** [comment]
Ждём pull request

**Comment by Orniflop** [comment]
Сделал
