### ISSUE TITLE
Исправить ошибки исправления :)

### ISSUE THREAD

**Issue by ro31337** [ro31337/rubyisforfun_ru#10]
<img width="358" alt="image" src="https://user-images.githubusercontent.com/1477672/209973009-fb0940a4-2d75-4b1c-9537-2fa8fffea585.png">

**Comment by Yuri-SN** [comment]
Pull request
#12

**Comment by ro31337** [comment]
@Yuri-SN благодарю, в одном месте исправилось, во втором осталось "директори" вместо "директории":

![image](https://user-images.githubusercontent.com/1477672/210123106-6fa98d53-520e-422f-a955-c0f1c82de9fa.png)

**Comment by Yuri-SN** [comment]
Пропустил это слово.. Поправлю и пришлю в следующем pull-request-е.

**Comment by ro31337** [comment]
Спасибо за исправления!
